import "./ditto.css";
import Tile from "./components/tile";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { text: "Lunes", text2: "12:00 - 21:00" },
    { text: "Martes", text2: "12:00 - 21:00" },
    { text: "Miércoles", text2: "12:00 - 21:00" },
    { text: "Jueves", text2: "12:00 - 21:00" },
    { text: "Viernes", text2: "12:00 - 21:00" },
    { text: "Sábado", text2: "12:00 - 21:00" },
    { text: "Domingo", text2: "15:00 - 21:00" }
];
const Tile_cids: string[][] = [
    ["n67", "n68", "n69", "n70", "n71", "n72", "n73"],
    ["n74", "n75", "n76", "n77", "n78", "n79", "n80"],
    ["n81", "n82", "n83", "n84", "n85", "n86", "n87"],
    ["n88", "n89", "n90", "n91", "n92", "n93", "n94"],
    ["n95", "n96", "n97", "n98", "n99", "n100", "n101"],
    ["n102", "n103", "n104", "n105", "n106", "n107", "n108"],
    ["n109", "n110", "n111", "n112", "n113", "n114", "n115"]
];

export default function Page() {
  return (
    <>
      <section className="box-content block" data-cid="n1">
        <article className="box-content block" data-cid="n2">
          <span className="box-content block" data-cid="n3">
            <hr className="box-content w-315.5 h-0 border border-inset border-border block my-2 overflow-hidden text-border max-md:w-[22.3125rem] md:max-lg:w-187.5 2xl:w-475.5" data-cid="n4" />
          </span>
          <div className="box-content block" data-cid="n5">
            <blockquote className="box-content block my-4 mx-10" data-cid="n6">
              <table className="w-100 h-70 table mx-auto [border-spacing:2px] max-md:-mr-[7.5625rem] max-md:ml-0" data-cid="n7" width="400">
                <tbody className="box-content h-69 table-row-group align-middle [border-spacing:2px]" data-cid="n8">
                  <tr className="box-content h-69 table-row align-middle [border-spacing:2px]" data-cid="n9">
                    <td className="box-content h-68.5 table-cell p-px align-middle [border-spacing:2px]" data-cid="n10">
                      <p className="box-content block my-4 text-center [border-spacing:2px]" data-cid="n11">
                        <a className="box-content inline text-primary underline cursor-pointer [border-spacing:2px]" data-cid="n12" data-component="link" href="/es/index.htm">
                          <img className="box-content w-46.5 h-46.5 inline overflow-clip aspect-[auto_186/186] [border-spacing:2px]" data-cid="n13" data-component="image" alt="energia piramidal" height="186" src="/assets/cloned/images/8eed3a17f499.jpg" width="186" />
                        </a>
                      </p>
                      {" "}
                      <p className="box-content block my-4 text-center [border-spacing:2px]" data-cid="n14">
                        {"SI SIGUE NAVEGANDO, SE ENTIENDE QUE ACEPTA NUESTROS "}
                        <a className="box-content inline text-primary underline cursor-pointer [border-spacing:2px]" data-cid="n15" data-component="link" href="/es/terminos_y_condiciones_avisos_legales_derechos_de_autor.htm">
                          <strong className="box-content inline font-bold [border-spacing:2px]" data-cid="n16">
                            TÉRMINOS Y GARANTÍAS LEGALES.
                          </strong>
                        </a>
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
              {" "}
              <h2 className="box-content block my-5 text-2xl font-bold leading-[1.6875rem] text-center" data-cid="n17" data-component="heading">
                PIRAMICASA® CDI Ciencia y Técnica de las Pirámides
                <br className="box-content inline" data-cid="n18" />
                {" "}
              </h2>
              {" "}
              <h3 className="box-content block my-[18.7px] text-[1.1875rem] font-bold leading-5.5" data-cid="n19" data-component="heading">
                <span className="box-content block" data-cid="n20">
                  <strong className="box-content inline font-black" data-cid="n21">
                    <a className="box-content inline text-primary underline cursor-pointer" data-cid="n22" data-component="link" href="/CONSTRUCCION/construccion-de-piramides.html" title="CONSTRUIR PIRÁMIDES">
                      CONSTRUCCIÓN de PIRÁMIDES Y FÓRMULAS
                    </a>
                  </strong>
                </span>
              </h3>
              {" "}
              <p className="box-content block my-4" data-cid="n23">
                <span className="box-content block" data-cid="n24">
                  <a className="box-content inline text-primary underline cursor-pointer" data-cid="n25" data-component="link" href="/GEOBIOLOGIA/geobiologia.html">
                    <strong className="box-content inline font-bold" data-cid="n26">
                      GEOBIOLOGÍA
                    </strong>
                  </a>
                  {" - "}
                  <strong className="box-content inline font-bold" data-cid="n27">
                    {" "}
                    <a className="box-content inline text-primary underline cursor-pointer" data-cid="n28" data-component="link" href="/GEOBIOLOGIA/Biografia_Wilhelm%20Reich.html">
                      BIOGRAFÍA WILHELM REICH
                    </a>
                  </strong>
                  <a className="box-content inline text-primary underline cursor-pointer" data-cid="n29" data-component="link" href="/GEOBIOLOGIA/Biografia_Wilhelm%20Reich.html">
                    {" "}
                  </a>
                  {" - "}
                  <a className="box-content inline text-primary underline cursor-pointer" data-cid="n30" data-component="link" href="/GEOBIOLOGIA/biones.html">
                    <strong className="box-content inline font-bold" data-cid="n31">
                      BIONES (Orbs
                    </strong>
                    )
                  </a>
                </span>
              </p>
              {" "}
              <p className="box-content block my-4" data-cid="n32">
                <span className="box-content block" data-cid="n33">
                  {"PUEDE DESCARGAR UN "}
                  <strong className="box-content inline font-bold" data-cid="n34">
                    <a className="box-content inline text-primary underline cursor-pointer" data-cid="n35" data-component="link" href="/dossier-basico-piramicasa" title="pirámides piramicasa">
                      PDF ILUSTRATIVO
                    </a>
                  </strong>
                  {" de Piramicasa®"}
                </span>
              </p>
              {" "}
              <p className="box-content block my-4" data-cid="n36">
                <strong className="box-content inline font-bold" data-cid="n37">
                  <a className="box-content inline text-primary underline cursor-pointer" data-cid="n38" data-component="link" href="/LIBROS/libros_piramides.htm">
                    LIBROS DE PIRÁMIDES (y otros del Autor)
                  </a>
                </strong>
              </p>
              {" "}
              <p className="box-content block my-4" data-cid="n39">
                <span className="box-content block" data-cid="n40">
                  <a className="box-content inline text-primary underline cursor-pointer" data-cid="n41" data-component="link" href="/es/index.htm">
                    <strong className="box-content inline font-bold" data-cid="n42">
                      Página de INIICIO
                    </strong>
                  </a>
                </span>
              </p>
              {" "}
            </blockquote>
            {" "}
          </div>
          {" "}
          <blockquote className="box-content block my-4 mx-10" data-cid="n43">
            <span className="box-content block" data-cid="n44">
              <span className="box-content inline" data-cid="n45">
                {" "}
                <h3 className="box-content block my-[18.7px] text-[1.1875rem] font-bold leading-5.5" data-cid="n46" data-component="heading">
                  Contacto directo (No nos responsabilizamos de las acciones de otros fabricantes)
                </h3>
                {" "}
              </span>
            </span>
          </blockquote>
          {" "}
        </article>
      </section>
      <section className="box-content block" data-cid="n47">
        <article className="box-content block" data-cid="n48">
          <div className="box-content block" data-cid="n49">
            <div className="box-content h-[6.1875rem] inline-block text-lg leading-[1.3125rem] max-md:h-30" data-cid="n50">
              <br className="box-content inline" data-cid="n51" />
              <div className="box-content block text-left" data-cid="n52">
                <blockquote className="box-content block my-4.5 mx-10" data-cid="n53">
                  <p className="box-content block my-4.5" data-cid="n54">
                    <span className="box-content block" data-cid="n55">
                      <span className="box-content inline" data-cid="n56">
                        <a className="box-content inline text-primary underline cursor-pointer" data-cid="n57" data-component="link" href="mailto:piramicasa@protonmail.com" target="_blank">
                          <strong className="box-content inline font-bold" data-cid="n58">
                            piramicasa@protonmail.com
                          </strong>
                        </a>
                        {" "}
                      </span>
                    </span>
                    <span className="box-content block" data-cid="n59">
                      <span className="box-content inline" data-cid="n60">
                        {"+34 681087539 - +34 639284787 (Whatsapp y Telegram) "}
                      </span>
                    </span>
                  </p>
                  {" "}
                </blockquote>
                {" "}
              </div>
            </div>
            <div className="box-content inline-block" data-cid="n61">
              {" "}
              <h2 className="box-content block my-5 text-2xl font-bold leading-[1.6875rem]" data-cid="n62" data-component="heading">
                HORARIO DE LLAMADA (de España)
              </h2>
              <hr className="box-content w-[25.6875rem] h-0 border border-inset border-border block my-2 overflow-hidden text-border max-md:w-[22.3125rem]" data-cid="n63" />
              <br className="box-content inline" data-cid="n64" />
              <span className="box-content inline" data-cid="n65">
                <table className="h-77.5 table [border-spacing:2px]" data-cid="n66">
                  {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
                </table>
              </span>
            </div>
            <div className="box-content block" data-cid="n116" />
          </div>
        </article>
      </section>
      <footer className="box-content block" data-cid="n117">
        <div className="box-content block" data-cid="n118">
          <span className="box-content inline" data-cid="n119">
            <div className="box-content block text-center" data-cid="n120">
              <a className="box-content inline text-primary underline cursor-pointer" data-cid="n121" data-component="link" href="https://twitter.com/@piramicasa" rel="noopener noreferrer" target="_blank" title="twitter">
                {" "}
              </a>
              <a className="box-content inline text-primary underline cursor-pointer" data-cid="n122" data-component="link" href="https://faceboook.com/piramicasa" rel="noopener noreferrer" target="_blank" title="facebook">
                {" "}
              </a>
              <a className="box-content inline text-primary underline cursor-pointer" data-cid="n123" data-component="link" href="https://instagram.com/osiris5293" rel="noopener noreferrer" target="_blank" title="instagram">
                {" "}
              </a>
              <a className="box-content inline text-primary underline cursor-pointer" data-cid="n124" data-component="link" href="https://youtube.com/piramicasa" rel="noopener noreferrer" target="_blank" title="youtube">
                {" "}
              </a>
              <a className="box-content inline text-primary underline cursor-pointer" data-cid="n125" data-component="link" href="/es/index.htm" rel="noopener noreferrer" title="other">
                {" "}
              </a>
            </div>
          </span>
        </div>
        <div className="box-content block" data-cid="n126" />
      </footer>
      {" "}
    </>
  );
}
