import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <div className="box-content block" data-cid="n1" id="fb-root" />
      {" "}
      <blockquote className="box-content block my-3.5 mx-10" data-cid="n2">
        <table className="w-[46.625rem] table mx-auto [border-spacing:2px] max-lg:w-[618.9px] max-md:mr-[-339.9px] max-md:ml-0 2xl:w-[1149.1px]" data-cid="n3" width="63%">
          <tbody className="box-content table-row-group align-middle [border-spacing:2px]" data-cid="n4">
            <tr className="box-content table-row align-middle [border-spacing:2px]" data-cid="n5">
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n6" width="17%">
                <b className="box-content inline font-bold [border-spacing:2px]" data-cid="n7">
                  <font className="box-content inline [border-spacing:2px]" data-cid="n8">
                    <img className="box-content w-25 h-25 inline overflow-clip aspect-[auto_100/100] [border-spacing:2px]" data-cid="n9" data-component="image" height="100" src="/assets/cloned/images/ed36b4e0a3e2.gif" width="100" />
                  </font>
                </b>
              </td>
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n10" width="12%" />
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n11" width="71%">
                <b className="box-content inline font-bold [border-spacing:2px]" data-cid="n12">
                  <font className="box-content inline [border-spacing:2px]" data-cid="n13">
                    <img className="box-content w-[31.3125rem] h-23 inline overflow-clip aspect-[auto_501/92] [border-spacing:2px]" data-cid="n14" data-component="image" height="92" src="/assets/cloned/images/abd4bebc65a5.gif" width="501" />
                  </font>
                </b>
              </td>
            </tr>
          </tbody>
        </table>
        {" "}
        <p className="box-content block my-4.5 text-color-001 text-lg font-bold leading-[1.3125rem] text-center" data-cid="n15" />
        {" "}
        <h1 className="box-content block my-3 text-color-001 text-lg font-bold leading-[1.3125rem] text-center" data-cid="n16" data-component="heading">
          PIRAMI-JOYAS DE PIRAMICASA
          <b className="box-content inline font-black" data-cid="n17">
            <font className="box-content inline" data-cid="n18">
              <br className="box-content inline" data-cid="n19" />
              {" "}
            </font>
            {" "}
          </b>
          {" "}
        </h1>
        {" "}
        <p className="box-content block my-3.5" data-cid="n20">
          <strong className="box-content inline text-base font-bold leading-4.5" data-cid="n21">
            <span className="box-content inline" data-cid="n22">
              LAS MEJORES JOYAS DEL MUNDO
            </span>
          </strong>
          <span className="box-content inline text-base font-bold leading-4.5" data-cid="n23">
            {", "}
            <span className="box-content inline" data-cid="n24">
              {"son sin duda las "}
            </span>
          </span>
          <span className="box-content inline font-bold" data-cid="n25">
            pirámides
          </span>
          <span className="box-content inline text-base font-bold leading-4.5" data-cid="n26">
            <span className="box-content inline" data-cid="n27">
              {" de "}
              <a className="box-content inline text-accent underline cursor-pointer" data-cid="n28" data-component="link" href="/es/index.htm">
                <span className="box-content inline [font-family:'Arial_Black',_Gadget,_sans-serif]" data-cid="n29">
                  Piramicasa
                </span>
              </a>
              {", que curan definitivamente todas las enfermedades reumáticas e infecciosas, así como la mayor parte de las dolencias metabólicas. "}
            </span>
          </span>
          <span className="box-content inline text-base leading-4.5" data-cid="n30">
            Pero si ya tienes y disfrutas de esa maravilla, es momento de empezar a ver las otras joyas, que hacen las delicias de los amantes de la belleza mineral y la estética.
          </span>
        </p>
        {" "}
        <blockquote className="box-content block my-3.5 mx-10" data-cid="n31">
          <blockquote className="box-content block my-3.5 mx-10" data-cid="n32">
            <p className="box-content block my-3.5" data-cid="n33">
              <a className="box-content inline text-accent underline cursor-pointer" data-cid="n34" data-component="link" href="/es/index.htm">
                <img className="box-content w-100.5 h-[31.3125rem] inline overflow-clip aspect-[auto_402/501]" data-cid="n35" data-component="image" alt="joyas-duda" height="501" src="/assets/cloned/images/10bb8901e9dd.jpg" width="402" />
              </a>
            </p>
            {" "}
          </blockquote>
          {" "}
          <p className="box-content block my-3.5" data-cid="n36">
            <span className="box-content inline text-base font-bold leading-4.5" data-cid="n37">
              <span className="box-content inline" data-cid="n38">
                <strong className="box-content inline font-black" data-cid="n39">
                  PRESENTAMOS LA LÍNEA de joyas exclusivas y únicas PIRAMIJOYAS.
                </strong>
              </span>
            </span>
          </p>
          {" "}
        </blockquote>
        {" "}
        <p className="box-content block my-3.5" data-cid="n40">
          <span className="box-content inline text-base leading-4.5" data-cid="n41">
            No hacemos "colecciones", porque evitamos repeticiones. Las muestras son una base pero cada joya es personalizada, única, de acuerdo a gustos personales..
          </span>
        </p>
        {" "}
        <p className="box-content h-13 block my-3.5 max-md:h-52 md:max-lg:h-22 2xl:h-auto" data-cid="n42">
          <span className="box-content inline text-base leading-4.5" data-cid="n43">
            Apenas presentamos aquí una idea general, porque en realidad diseñamos cada joya junto con nuestros usuarios.
          </span>
          {" "}
          <span className="box-content inline text-base leading-4.5" data-cid="n44">
            {"La variedad es infinita. Usamos oro 18 Kilates, tanto en amarillo como en oro blanco de igual kilataje, y para algunas creaciones, platino o combinación de oro y platino. "}
          </span>
          No usamos plata, salvo en excepciones, cuando nuestros orfrbres nos recomiendan usarla para un contraste o fondo de una parte de una pieza de oro amarillo.
        </p>
        {" "}
        <p className="box-content block my-3.5 max-md:h-39 md:max-lg:h-17 2xl:h-8.5" data-cid="n45">
          <span className="box-content inline text-base leading-4.5" data-cid="n46">
            {"En esta sección podrás conocer mucho sobre joyería, sobre los "}
          </span>
          <span className="box-content inline text-base font-bold leading-4.5" data-cid="n47">
            metales preciosos
          </span>
          <span className="box-content inline text-base leading-4.5" data-cid="n48">
            {", sobre las "}
          </span>
          <span className="box-content inline text-base font-bold leading-4.5" data-cid="n49">
            piedras preciosas y semipreciosas
          </span>
          <span className="box-content inline text-base leading-4.5" data-cid="n50">
            , sus calidades, origen, valores y mucho más.
          </span>
          {" Utilizamos más infografía que fotos de los diseños, ya que éstas sólo se pueden publicar con autorización expesa de los propietarios."}
        </p>
        {" "}
        <p className="box-content block my-3.5" data-cid="n51">
          {"Nuestra política de privacidad es tan estricta en este tema como con nuestros "}
          <a className="box-content inline text-accent underline cursor-pointer" data-cid="n52" data-component="link" href="/es/index.htm">
            <strong className="box-content inline font-bold" data-cid="n53">
              productos piramidales
            </strong>
          </a>
          .
        </p>
        {" "}
        <p className="box-content h-24 block my-3.5 max-md:h-108 md:max-lg:h-44 2xl:h-16" data-cid="n54">
          {"Brindamos un servicio muy completo y perfecto, con diseño personalizado, elaboración con orfobres de gran profesionalidad, selección de gemas certificadas en establecimientos absolutamente confiables, con más de cuarenta años en el mercado de las piedras preciosas. No hacemos \"venta online\", sino mediante contacto directo, para definir medidas, pesos, tallas, materiales y diseños, que requieren una comunicación fluida para determinar con exactitud todos los detalles, tanto en anillos, como en "}
          <strong className="box-content inline font-bold" data-cid="n55">
            pulseras, collares, colgantes, broches, pendientes
          </strong>
          {" o cualquier otra "}
          <strong className="box-content inline font-bold" data-cid="n56">
            joya
          </strong>
          . Podemos hacer lo que nos soliciten, con modelos de cualquier cultura del mundo y en cualquier estilo, pero nuestra especialidad es la joyería egipcia. Conocemos en profundidad la simbología y su significado metafísico real, al margen de las teorías de la egiptología ortodoxa basada en teoría inglesas de hace doscientos años. Es decir que nuestras joyas tienen, además de la calidad y belleza que otorgan las gemas y el metal, significados profundos que explicamos con lujo de detalle a quienes las usan.
        </p>
        {" "}
        <p className="box-content block my-3.5" data-cid="n57">
          IDIOMAS: Mediante nuestros representantes autorizados, que son el staff de Piramicasa para todo el mundo, podemos atender en español, inglés, francés, alemán y árabe. Para otros idiomas usamos herramientas tecnológias adecuadas, pero en cualquier caso, la comunicación es fluida y armónica, porque adquirir nuestras joyas o nuestros productos piramidales representa para nosotros una relación muy especial, que trasciende la mera cordialidad habitual del mercado.
        </p>
        {" "}
        <p className="box-content block my-3.5" data-cid="n58">
          Estos son algunos de los diseños básicos y generales, pero recuerda que no tenemos limitaciones. Aunque luego lo agregaremos a esta web, puedes consultar por collares, colganes, pulseras, diademas, broches y cualquier tipo de joya personalizada que desees.
        </p>
        {" "}
        <table className="w-[36.8125rem] h-[20.3625rem] table [border-spacing:2px]" data-cid="n59" width="200">
          <tbody className="box-content h-[20.1125rem] table-row-group align-middle [border-spacing:2px]" data-cid="n60">
            <tr className="box-content h-[15.4375rem] table-row align-middle [border-spacing:2px]" data-cid="n61">
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n62">
                <a className="box-content inline text-accent underline cursor-pointer [border-spacing:2px]" data-cid="n63" data-component="link" href="/anillos.html">
                  <img className="box-content w-72 h-[15.3125rem] inline overflow-clip aspect-[auto_288/245] [border-spacing:2px]" data-cid="n64" data-component="image" alt="anillo de oro" height="245" src="/assets/cloned/images/d951c9e67aac.jpg" width="288" />
                </a>
              </td>
              <td className="box-content h-[15.3125rem] table-cell p-px align-middle text-color-001 text-lg font-bold leading-[1.3125rem] text-center [border-spacing:2px]" data-cid="n65">
                <p className="box-content block my-4.5 [border-spacing:2px]" data-cid="n66">
                  <a className="box-content inline text-accent underline cursor-pointer [border-spacing:2px]" data-cid="n67" data-component="link" href="/joyas-exclusivas.htm" title="JOYAS">
                    MÁS JOYAS EXCLUSIVAS
                  </a>
                </p>
                {" "}
                <p className="box-content block my-4.5 [border-spacing:2px]" data-cid="n68">
                  <a className="box-content inline text-accent underline cursor-pointer [border-spacing:2px]" data-cid="n69" data-component="link" href="/joyas-exclusivas.htm">
                    (DIAMANTES Y ESMERALDAS)
                  </a>
                </p>
              </td>
              <td className="box-content h-[15.3125rem] table-cell p-px align-middle text-color-001 text-lg font-bold leading-[1.3125rem] text-center [border-spacing:2px]" data-cid="n70">
                PRÓXIMAMENTE MÁS SECCIONES DE JOYERÍA PERSONALIZADA
              </td>
            </tr>
            <tr className="box-content h-[4.55rem] table-row align-middle [border-spacing:2px]" data-cid="n71">
              <td className="box-content h-[4.425rem] table-cell p-px align-middle [border-spacing:2px]" data-cid="n72">
                <blockquote className="box-content block my-3.5 mx-10 [border-spacing:2px]" data-cid="n73">
                  <h2 className="box-content block my-[1.0875rem] text-[1.3125rem] font-bold leading-6 [border-spacing:2px]" data-cid="n74" data-component="heading">
                    <a className="box-content inline text-accent underline cursor-pointer [border-spacing:2px]" data-cid="n75" data-component="link" href="/anillos.html">
                      <strong className="box-content inline [font-family:'Arial_Black',_Gadget,_sans-serif] text-base leading-4.5 [border-spacing:2px]" data-cid="n76">
                        <span className="box-content inline text-clr-6 text-center cursor-text [border-spacing:2px]" data-cid="n77">
                          VER SECCIÓN DE ANILLOS
                        </span>
                      </strong>
                    </a>
                  </h2>
                  {" "}
                </blockquote>
              </td>
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n78" />
              <td className="box-content table-cell p-px align-middle [border-spacing:2px]" data-cid="n79" />
            </tr>
          </tbody>
        </table>
        {" "}
        <p className="box-content block my-3.5" data-cid="n80" />
        {" "}
        <p className="box-content block my-3.5" data-cid="n81">
          <a className="box-content inline text-accent underline cursor-pointer" data-cid="n82" data-component="link" href="/es/index.htm">
            <img className="box-content w-83.5 h-[14.0625rem] inline overflow-clip aspect-[auto_334/225]" data-cid="n83" data-component="image" alt="purámides maravillosas" height="225" src="/assets/cloned/images/f2d5a0bf0263.gif" width="334" />
          </a>
        </p>
        {" "}
        <p className="box-content block my-3.5" data-cid="n84" />
        {" "}
        <div className="box-content block" data-cid="n85" />
        <table className="w-[37.7375rem] h-[24.675rem] border-[3px] border-outset border-border table mx-auto [border-spacing:2px] max-lg:w-103.5 max-md:-mr-[8.4375rem] max-md:ml-0 2xl:w-[58.1375rem]" data-cid="n86" height="101" width="51%">
          <tbody className="box-content h-[24.05rem] table-row-group align-middle [border-spacing:2px]" data-cid="n87">
            <tr className="box-content h-[24.05rem] table-row align-middle [border-spacing:2px]" data-cid="n88">
              <td className="box-content h-[23.8rem] border border-inset border-border table-cell p-px align-middle bg-clr-7 [border-spacing:2px]" data-cid="n89" height="101" width="86%">
                <h2 className="box-content h-86.5 block my-[1.0875rem] text-[1.3125rem] font-bold leading-6 text-center [border-spacing:2px]" data-cid="n90" data-component="heading">
                  <span className="box-content inline text-color-001 text-lg leading-[1.3125rem] [border-spacing:2px]" data-cid="n91">
                    <b className="box-content inline font-black [border-spacing:2px]" data-cid="n92">
                      <font className="box-content inline [border-spacing:2px]" data-cid="n93">
                        <font className="box-content inline text-clr-8 text-[0.8125rem] leading-[0.9375rem] [border-spacing:2px]" data-cid="n94">
                          VIAJE A EGIPTO DE LUJO 5* SUPERIOR
                          <br className="box-content inline [border-spacing:2px]" data-cid="n95" />
                          {" CON INVESTIGADORES Y EXPERTOS"}
                        </font>
                        <font className="box-content inline text-[0.8125rem] leading-[0.9375rem] [border-spacing:2px]" data-cid="n96">
                          <br className="box-content inline [border-spacing:2px]" data-cid="n97" />
                          {" "}
                        </font>
                      </font>
                    </b>
                  </span>
                  <span className="box-content inline text-base leading-4.5 bg-background bg-no-repeat [border-spacing:2px]" data-cid="n98">
                    <b className="box-content inline font-black [border-spacing:2px]" data-cid="n99">
                      <font className="box-content inline [border-spacing:2px]" data-cid="n100">
                        <font className="box-content inline text-[0.8125rem] leading-[0.9375rem] [border-spacing:2px]" data-cid="n101">
                          (Al margen de las explicaciones turísticas masificadas)
                        </font>
                      </font>
                    </b>
                  </span>
                  <b className="box-content inline font-black [border-spacing:2px]" data-cid="n102">
                    <font className="box-content inline [border-spacing:2px]" data-cid="n103">
                      <br className="box-content inline [border-spacing:2px]" data-cid="n104" />
                      {" "}
                      <a className="box-content inline text-accent underline cursor-pointer [border-spacing:2px]" data-cid="n105" data-component="link" href="/EGIPTO/ViajeEgipto.htm">
                        <img className="box-content w-100 h-73 inline overflow-clip aspect-[auto_400/292] [border-spacing:2px]" data-cid="n106" data-component="image" alt="viaje a egipto" height="292" src="/assets/cloned/images/9e24b96282ef.jpg" width="400" />
                      </a>
                      {" "}
                    </font>
                    {" "}
                  </b>
                </h2>
                {" "}
              </td>
            </tr>
          </tbody>
        </table>
        {" "}
        <p className="box-content block my-3.5 [text-align:-webkit-center]" data-cid="n107">
          <b className="box-content inline font-bold" data-cid="n108">
            <font className="box-content inline" data-cid="n109">
              <br className="box-content inline" data-cid="n110" />
              {" PIRAMICASA te agradece que difundas esta lista de correo entre tus contactos. En Telegram "}
              <a className="box-content inline text-accent underline cursor-pointer" data-cid="n111" data-component="link" href="https://t.me/Piramicasa" target="_blank">
                t.me/Piramicasa
              </a>
            </font>
          </b>
          <b className="box-content inline font-bold" data-cid="n112">
            <font className="box-content inline" data-cid="n113">
              <br className="box-content inline" data-cid="n114" />
              {" "}
            </font>
          </b>
        </p>
        {" "}
        <table className="w-[31.3125rem] h-[5.4375rem] table p-[0.3125rem] bg-background" data-cid="n115" width="501">
          <tbody className="box-content h-[4.8125rem] table-row-group align-middle" data-cid="n116">
            <tr className="box-content table-row align-middle" data-cid="n117">
              <td className="box-content table-cell p-px align-middle" data-cid="n118" />
            </tr>
            <tr className="box-content h-4.5 table-row align-middle" data-cid="n119">
              <td className="box-content h-4 table-cell py-px pr-px pl-[0.3125rem] align-middle" data-cid="n120">
                <b className="box-content inline font-bold" data-cid="n121">
                  <font className="box-content inline" data-cid="n122">
                    Suscribirte a PIRAMICASA (Foro moderado, no satura correo)
                  </font>
                </b>
              </td>
            </tr>
            <tr className="box-content h-[1.4375rem] table-row align-middle" data-cid="n123">
              <td className="box-content h-[1.3125rem] table-cell py-px pr-px pl-[0.3125rem] align-middle" data-cid="n124">
                <b className="box-content inline font-bold" data-cid="n125">
                  <font className="box-content inline" data-cid="n126">
                    {" Correo electr�nico: "}
                    <input className="box-content w-[10.5625rem] h-[0.9375rem] border-2 border-inset border-muted-foreground inline-block py-px px-0.5 overflow-clip [font-family:Arial] text-[0.8125rem] font-normal leading-[0.9375rem] bg-background cursor-text" data-cid="n127" data-component="input" name="email" type="text" />
                    {" "}
                    <input className="w-20.5 h-[1.3125rem] border-2 border-outset border-foreground inline-block py-px px-1.5 overflow-clip [font-family:Arial] text-[0.8125rem] font-normal leading-[0.9375rem] text-center whitespace-pre text-nowrap bg-clr-0 cursor-default" data-cid="n128" data-component="button" name="sub" type="submit" value="Suscribirse" />
                    {" "}
                  </font>
                </b>
              </td>
            </tr>
            <tr className="box-content h-4.5 table-row align-middle" data-cid="n129">
              <td className="box-content h-4 table-cell p-px align-middle [text-align:-webkit-right]" data-cid="n130">
                <font className="box-content inline" data-cid="n131">
                  <a className="box-content inline text-accent underline cursor-pointer" data-cid="n132" data-component="link" href="http://groups.google.com/group/piramicasa">
                    Consultar este grupo
                  </a>
                  {" "}
                </font>
              </td>
            </tr>
          </tbody>
        </table>
        {" "}
        <p className="box-content block my-3.5" data-cid="n133" />
        {" "}
        <p className="box-content block my-3.5" data-cid="n134">
          <b className="box-content inline font-bold" data-cid="n135">
            <font className="box-content inline" data-cid="n136">
              <br className="box-content inline" data-cid="n137" />
              {" "}
            </font>
          </b>
        </p>
        {" "}
      </blockquote>
      {" "}
    </>
  );
}
