import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-10 leading-7">
      <h1 className="mb-4 text-4xl font-bold">Anillos personalizados</h1>
      <p className="mb-4">
        Seccion de consulta para anillos personalizados dentro de PIRAMIJOYAS, con enfoque en diseno
        a medida, seleccion de materiales y acompanamiento artesanal.
      </p>

      <section className="mb-8 rounded-lg border p-6">
        <h2 className="mb-3 text-2xl font-semibold">Opciones de trabajo</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>Diseno exclusivo segun talla, estilo y simbolismo.</li>
          <li>Metales y gemas seleccionadas con criterios tecnicos.</li>
          <li>Proceso de validacion antes de fabricacion final.</li>
        </ul>
      </section>

      <div className="flex flex-wrap gap-4">
        <a className="text-blue-700 underline" href="/JOYAS/joyas.htm">Volver a Joyas</a>
        <a className="text-blue-700 underline" href="/es/index.htm">Volver a portada</a>
      </div>
    </main>
  );
}
