import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-10 leading-7">
      <h1 className="mb-4 text-4xl font-bold">Joyas exclusivas</h1>
      <p className="mb-4">
        Espacio interno para piezas de alta personalizacion, incluyendo combinaciones de diamantes,
        esmeraldas y otros disenos unicos por encargo.
      </p>

      <section className="mb-8 rounded-lg border p-6">
        <h2 className="mb-3 text-2xl font-semibold">Linea destacada</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>Propuestas exclusivas en metales nobles.</li>
          <li>Gemologia orientada a calidad y durabilidad.</li>
          <li>Asesoria personalizada para regalo o coleccion privada.</li>
        </ul>
      </section>

      <div className="flex flex-wrap gap-4">
        <a className="text-blue-700 underline" href="/JOYAS/joyas.htm">Volver a Joyas</a>
        <a className="text-blue-700 underline" href="/anillos.html">Ir a Anillos</a>
      </div>
    </main>
  );
}
